In [152]:
from sqlalchemy import create_engine
import pandas as pd

In [153]:
engine_hdb = create_engine('mysql://airflow_user:password@localhost:3306/HDB_Data')

str_sql = f'''
SELECT * FROM raw_onemap_planning_areas
'''
df_planning_area = pd.read_sql(sql=str_sql, con=engine_hdb)

str_sql = f'''
SELECT * FROM raw_onemap_transport_school
'''
df_transport_school = pd.read_sql(sql=str_sql, con=engine_hdb)

str_sql = f'''
SELECT * FROM raw_onemap_transport_work
'''
df_transport_work = pd.read_sql(sql=str_sql, con=engine_hdb)

str_sql = f'''
SELECT * FROM raw_onemap_dwelling
'''
df_dwelling = pd.read_sql(sql=str_sql, con=engine_hdb)

str_sql = f'''
SELECT * FROM raw_onemap_tenancy
'''
df_tenancy = pd.read_sql(sql=str_sql, con=engine_hdb)

engine_hdb.dispose()

## **Finding DataFrames with Nulls**

In [154]:
for df in [df_planning_area, df_transport_school, df_transport_work, df_dwelling, df_tenancy]:
    print(df.isna().sum())

planning_area    0
year             0
_fp              0
dtype: int64
planning_area                  0
year                           0
bus                           42
mrt                           42
mrt_bus                       42
mrt_car                       42
mrt_other                     42
taxi                          42
car                           42
pvt_chartered_bus             42
lorry_pickup                  42
motorcycle_scooter            42
others                        42
no_transport_required         42
other_combi_mrt_or_bus        42
mrt_lrt_only                  42
mrt_lrt_and_bus               42
other_combi_mrt_lrt_or_bus    42
taxi_pvt_hire_car_only        42
pvt_chartered_bus_van         42
_fp                            0
dtype: int64
planning_area                  0
year                           0
bus                           42
mrt                           42
mrt_bus                       42
mrt_car                       42
mrt_other                     42
taxi                          42
car                           42
pvt_chartered_bus             42
lorry_pickup                  42
motorcycle_scooter            42
others                        42
no_transport_required         42
other_combi_mrt_or_bus        42
mrt_lrt_only                  42
mrt_lrt_and_bus               42
other_combi_mrt_lrt_or_bus    42
taxi_pvt_hire_car_only        42
pvt_chartered_bus_van         42
_fp                            0
dtype: int64
planning_area                         0
year                                  0
hdb_1_and_2_room_flats               69
hdb_3_room_flats                     69
hdb_4_room_flats                     69
hdb_5_room_and_executive_flats       69
condominiums_and_other_apartments    69
landed_properties                    69
others                               69
_fp                                   0
dtype: int64
planning_area     0
year              0
owner            42
tenant           42
others           42
_fp               0
dtype: int64

In [155]:
df_transport_school[df_transport_school.isnull().any(axis=1)]

,planning_area,year,bus,mrt,mrt_bus,mrt_car,mrt_other,taxi,car,pvt_chartered_bus,...,motorcycle_scooter,others,no_transport_required,other_combi_mrt_or_bus,mrt_lrt_only,mrt_lrt_and_bus,other_combi_mrt_lrt_or_bus,taxi_pvt_hire_car_only,pvt_chartered_bus_van,_fp
12,BOON LAY,2010,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,bb97f5aa45e7dec920ac0ed689bb04be5755ab866ebe11...
15,BOON LAY/PIONEER,2000,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,eb8b85621f401a600ea0352008ca7c092e20aa3280c77c...
32,CENTRAL WATER CATCHMENT,2000,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,470a762d4f68790166da8886933789b244f5db616e676e...
33,CENTRAL WATER CATCHMENT,2010,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,5d6fe7be6ec5cddd56060deff5a5d5820fc0ca4f0b2e17...
40,CHANGI BAY,2000,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,07118f349a63ecbe197c7fd462c0b503fd8fef875ceb28...
41,CHANGI BAY,2010,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,6389cf880818da2d1fc009e2cc7a56d2b93de37591fe98...
76,LIM CHU KANG,2000,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,daff0cd619a96139c921d557bc957cbb1b9f41531e094d...
77,LIM CHU KANG,2010,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,fc4ec02be9730a4889f9a158193795f1d6676a9e6aaf1a...
80,MANDAI,2000,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,2a80ce1e6613298b7c68c7d0791f4ba7027cd46645a298...
84,MARINA EAST,2000,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,0196860ea7298e822bc8839a044df79f9ac81e8446e2cd...
85,MARINA EAST,2010,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,8c3c4842cc0de970d9060acc4ca32119ef3a28db8e353d...
88,MARINA SOUTH,2000,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,15b38dccc6e30388238e0ae7ea107035e050d408bc779b...
89,MARINA SOUTH,2010,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,16d60bf996ddad4b3e559504026506569b191ca53db071...
96,MUSEUM,2000,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,5e94cf0abfe94146e0002703c9c52048b273b7ee4a5cf0...
97,MUSEUM,2010,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,ca502f327393835e3ef2aab502670eb628f817293ee027...
104,NORTH-EASTERN ISLANDS,2000,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,b18ca9562e901e967d3ef6935aacef81510b4c5f6b1904...
105,NORTH-EASTERN ISLANDS,2010,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,ec6f589f167dff0270584b35bd9e938441b18fa1fbf2ff...
112,ORCHARD,2000,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,c95db05065acacbfa6d256b013e410a2805d02a57ec81a...
113,ORCHARD,2010,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,4f68da6bc09962cb3ffe216bde201e6cc7a171b6c6e044...
124,PAYA LEBAR,2000,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,4ef1c3158060b6fdc02ab0797a1daa4f9a9aef32ca176e...
125,PAYA LEBAR,2010,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,884eb3f5cfa60c2dd983354ae9acb757cb3e7bdf76a896...
128,PIONEER,2010,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,5741392a08a55db9a270c462c18e3793954316ac51bbdf...
131,PUNGGOL,2000,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,0b8c0b675a47b9ada10cfb3e0a02e76f79d9233a5d9b30...
147,SELETAR,2000,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,b2854239c1e5b4e22a62a135f63ae1d050e03ebc2d112d...
148,SELETAR,2010,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,1aa13db3b3890aa352a9745c5c046129e9e04918aca5a0...
163,SIMPANG,2000,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,0a2e524dd1fefb1dca564eba604e4d46e92321019a55ce...
164,SIMPANG,2010,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,8acc9322986d90b8b2f454c359f81b2c402c85448765ed...
167,SINGAPORE RIVER,2000,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,b429fc2a936a60a381a923e2132a50ccdbb15d43c63305...
171,SOUTHERN ISLANDS,2000,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,6a1d58626774c67b3634c8bbc69c2ef370d2ddd93bd12f...
172,SOUTHERN ISLANDS,2010,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,2e24a54cb3f8512dd82da45839251b817e21f3cb490861...
175,STRAITS VIEW,2000,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,2cb973bd06607ce3e6053d9f19e1155ab5b0f6344bd731...
176,STRAITS VIEW,2010,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,0ea8ca389dffdf7ba5d3530809577aec3c97b80d7affa8...
179,SUNGEI KADUT,2000,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,800b75b7616bc0c8487170b16047a01fbb24fabb7817ad...
180,SUNGEI KADUT,2010,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,69028dc9c56c309d20317ea27ae7a9f63a9a2283889616...
191,TENGAH,2000,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,6befaa756eac02f68af476b1989117f26e4b003afc2940...
192,TENGAH,2010,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,eff2ebe648f82b8e56c1ddd11f815b6720bb32ee82e22b...
199,TUAS,2000,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,68fed366ff0e48c123342d49a99f92bbfce2dd8f0be162...
200,TUAS,2010,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,12fa4e746e9134ed79720b5fdfa8051d5a3c77a1026940...
203,WESTERN ISLANDS,2000,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,21984e07f53c3ad2670b4be7a17fc40b05bd1f46e0f76c...
204,WESTERN ISLANDS,2010,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,c171fec842746229dd3b419a934f5d5b0a66c90b609cca...
207,WESTERN WATER CATCHMENT,2000,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,88746e54bf3ec353c10dfc282bdbb7876ea8ae902a406d...
208,WESTERN WATER CATCHMENT,2010,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,de81ab74db93225a0efd4d686ecc44c191419a7a066941...

In [156]:
df_transport_work[df_transport_work.isnull().any(axis=1)]

,planning_area,year,bus,mrt,mrt_bus,mrt_car,mrt_other,taxi,car,pvt_chartered_bus,...,motorcycle_scooter,others,no_transport_required,other_combi_mrt_or_bus,mrt_lrt_only,mrt_lrt_and_bus,other_combi_mrt_lrt_or_bus,taxi_pvt_hire_car_only,pvt_chartered_bus_van,_fp
12,BOON LAY,2010,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,bb97f5aa45e7dec920ac0ed689bb04be5755ab866ebe11...
15,BOON LAY/PIONEER,2000,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,eb8b85621f401a600ea0352008ca7c092e20aa3280c77c...
32,CENTRAL WATER CATCHMENT,2000,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,470a762d4f68790166da8886933789b244f5db616e676e...
33,CENTRAL WATER CATCHMENT,2010,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,5d6fe7be6ec5cddd56060deff5a5d5820fc0ca4f0b2e17...
40,CHANGI BAY,2000,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,07118f349a63ecbe197c7fd462c0b503fd8fef875ceb28...
41,CHANGI BAY,2010,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,6389cf880818da2d1fc009e2cc7a56d2b93de37591fe98...
76,LIM CHU KANG,2000,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,daff0cd619a96139c921d557bc957cbb1b9f41531e094d...
77,LIM CHU KANG,2010,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,fc4ec02be9730a4889f9a158193795f1d6676a9e6aaf1a...
80,MANDAI,2000,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,2a80ce1e6613298b7c68c7d0791f4ba7027cd46645a298...
84,MARINA EAST,2000,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,0196860ea7298e822bc8839a044df79f9ac81e8446e2cd...
85,MARINA EAST,2010,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,8c3c4842cc0de970d9060acc4ca32119ef3a28db8e353d...
88,MARINA SOUTH,2000,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,15b38dccc6e30388238e0ae7ea107035e050d408bc779b...
89,MARINA SOUTH,2010,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,16d60bf996ddad4b3e559504026506569b191ca53db071...
96,MUSEUM,2000,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,5e94cf0abfe94146e0002703c9c52048b273b7ee4a5cf0...
97,MUSEUM,2010,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,ca502f327393835e3ef2aab502670eb628f817293ee027...
104,NORTH-EASTERN ISLANDS,2000,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,b18ca9562e901e967d3ef6935aacef81510b4c5f6b1904...
105,NORTH-EASTERN ISLANDS,2010,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,ec6f589f167dff0270584b35bd9e938441b18fa1fbf2ff...
112,ORCHARD,2000,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,c95db05065acacbfa6d256b013e410a2805d02a57ec81a...
113,ORCHARD,2010,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,4f68da6bc09962cb3ffe216bde201e6cc7a171b6c6e044...
124,PAYA LEBAR,2000,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,4ef1c3158060b6fdc02ab0797a1daa4f9a9aef32ca176e...
125,PAYA LEBAR,2010,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,884eb3f5cfa60c2dd983354ae9acb757cb3e7bdf76a896...
128,PIONEER,2010,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,5741392a08a55db9a270c462c18e3793954316ac51bbdf...
131,PUNGGOL,2000,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,0b8c0b675a47b9ada10cfb3e0a02e76f79d9233a5d9b30...
147,SELETAR,2000,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,b2854239c1e5b4e22a62a135f63ae1d050e03ebc2d112d...
148,SELETAR,2010,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,1aa13db3b3890aa352a9745c5c046129e9e04918aca5a0...
163,SIMPANG,2000,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,0a2e524dd1fefb1dca564eba604e4d46e92321019a55ce...
164,SIMPANG,2010,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,8acc9322986d90b8b2f454c359f81b2c402c85448765ed...
167,SINGAPORE RIVER,2000,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,b429fc2a936a60a381a923e2132a50ccdbb15d43c63305...
171,SOUTHERN ISLANDS,2000,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,6a1d58626774c67b3634c8bbc69c2ef370d2ddd93bd12f...
172,SOUTHERN ISLANDS,2010,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,2e24a54cb3f8512dd82da45839251b817e21f3cb490861...
175,STRAITS VIEW,2000,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,2cb973bd06607ce3e6053d9f19e1155ab5b0f6344bd731...
176,STRAITS VIEW,2010,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,0ea8ca389dffdf7ba5d3530809577aec3c97b80d7affa8...
179,SUNGEI KADUT,2000,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,800b75b7616bc0c8487170b16047a01fbb24fabb7817ad...
180,SUNGEI KADUT,2010,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,69028dc9c56c309d20317ea27ae7a9f63a9a2283889616...
191,TENGAH,2000,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,6befaa756eac02f68af476b1989117f26e4b003afc2940...
192,TENGAH,2010,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,eff2ebe648f82b8e56c1ddd11f815b6720bb32ee82e22b...
199,TUAS,2000,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,68fed366ff0e48c123342d49a99f92bbfce2dd8f0be162...
200,TUAS,2010,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,12fa4e746e9134ed79720b5fdfa8051d5a3c77a1026940...
203,WESTERN ISLANDS,2000,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,21984e07f53c3ad2670b4be7a17fc40b05bd1f46e0f76c...
204,WESTERN ISLANDS,2010,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,c171fec842746229dd3b419a934f5d5b0a66c90b609cca...
207,WESTERN WATER CATCHMENT,2000,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,88746e54bf3ec353c10dfc282bdbb7876ea8ae902a406d...
208,WESTERN WATER CATCHMENT,2010,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,de81ab74db93225a0efd4d686ecc44c191419a7a066941...

In [157]:
df_tenancy[df_tenancy.isnull().any(axis=1)]

,planning_area,year,owner,tenant,others,_fp
12,BOON LAY,2010,None,None,None,8c78d2b1420448080f7c1ac611dde94a2825640d7074e6...
15,BOON LAY/PIONEER,2000,None,None,None,9fbed945cec7d33b2d310ab9fcddfe333da0d8789b6bc4...
32,CENTRAL WATER CATCHMENT,2000,None,None,None,2b6ce587e517d7f779ba7d5cf421ed28df4b300b54b827...
33,CENTRAL WATER CATCHMENT,2010,None,None,None,d6c6b4baef978841b21c66d3a29a27244a08f6a03af0ef...
40,CHANGI BAY,2000,None,None,None,8c4d0a58f5fe122de9bd61177b07615d0e601baf1b81fc...
41,CHANGI BAY,2010,None,None,None,49d8fc9b150cab32a3f32b4ee89e212a63ca5ac1467922...
76,LIM CHU KANG,2000,None,None,None,0800d628e8b4bc70a20016898b94387003833e45d49406...
77,LIM CHU KANG,2010,None,None,None,46c91cddbbcf1e03868527e45b2d2a06af702efd822b69...
80,MANDAI,2000,None,None,None,d3d60c30ff781feaf070ca9e6f4fe480b92d67e3f88b5e...
84,MARINA EAST,2000,None,None,None,7530ac3714b6fca90a30045b5fc4995f80f4b7b49d49e7...
85,MARINA EAST,2010,None,None,None,9152ecd9ecb12b7befaa2dcc66e7b15827be99451bb7f4...
88,MARINA SOUTH,2000,None,None,None,45b170b9dd68400f76b5d9946b639d2242de0589028f06...
89,MARINA SOUTH,2010,None,None,None,74688c0a23875723a141c11c66b1f91ea6c205c4776451...
96,MUSEUM,2000,None,None,None,7de08ec563decf7af8fd6f19899ed0f9036ccc2f5a5965...
97,MUSEUM,2010,None,None,None,d81b895d4d30034605a323748065ac52599059388ad2a9...
104,NORTH-EASTERN ISLANDS,2000,None,None,None,8bab7408f238a5f13fb76a8a00292d0c45abe4a83fe698...
105,NORTH-EASTERN ISLANDS,2010,None,None,None,b612a87dad0134f23cc981f720872b60cbdb09b6d40e05...
112,ORCHARD,2000,None,None,None,da264e14e6cbbb444dcc0a3f9d39c360c55b960e8a61fd...
113,ORCHARD,2010,None,None,None,01f8b5d95b4f542730b325b6c2ee79c145f25cb9bff36f...
124,PAYA LEBAR,2000,None,None,None,54e1deb5c3c4a07869fc641496064a697d9fd2604190cd...
125,PAYA LEBAR,2010,None,None,None,bd13e754e569583c198c3c653098f004e3e282542aa199...
128,PIONEER,2010,None,None,None,4cbf6ff15555c89544bf63ab5e58052ddf9f0055a35e49...
131,PUNGGOL,2000,None,None,None,59359e3fa36481f55dca71fbec33dade5239d5b99b8e03...
147,SELETAR,2000,None,None,None,ef6ae9f8367224ab63ada23a08a9f680e4eb1480bdfc20...
148,SELETAR,2010,None,None,None,76b7d091b7d46902384aea7b257e4ca564413b1c3c7180...
163,SIMPANG,2000,None,None,None,6dae270a031d340fb19aa450512153025a61d3fe558fd7...
164,SIMPANG,2010,None,None,None,8ff2eeb2da16b05a226204fd93cc2ce7c6e870909ea4d6...
167,SINGAPORE RIVER,2000,None,None,None,de1857fbd566125a2dbed699221a11da3930438343cfdd...
171,SOUTHERN ISLANDS,2000,None,None,None,7f8f60e911fe3c8ae419d9ad1bb00b10ef8c7fd31c3dd2...
172,SOUTHERN ISLANDS,2010,None,None,None,28e888da7e9d9c009fb335872291db01e7f748dc01bae8...
175,STRAITS VIEW,2000,None,None,None,42540d151dfdf5ebf379bc4d31905fcd7a34b714903475...
176,STRAITS VIEW,2010,None,None,None,6b5cab6167c84e7cfeda5e483cffd2f0e51641e63676b0...
179,SUNGEI KADUT,2000,None,None,None,0f18b824100129e65ee411d496c4a89173ac0eb0d6eb13...
180,SUNGEI KADUT,2010,None,None,None,c9621fb1e4356952d35dfa10608193f82f3cd731ed00a2...
191,TENGAH,2000,None,None,None,74a516565fec0d2ecd795791b8c4803def48c805ad143e...
192,TENGAH,2010,None,None,None,6659a4fb0e2955e9f510b83372439440546fdaf665f852...
199,TUAS,2000,None,None,None,2b085a2ccb351e5c49d6a7713463a7a135074311c26c53...
200,TUAS,2010,None,None,None,0e100982b08b861e94d1d7fa3e86281ef0613079f8b597...
203,WESTERN ISLANDS,2000,None,None,None,ebd18da74601f9cd1854ed96c4ae8aee190d86863e4fba...
204,WESTERN ISLANDS,2010,None,None,None,955adb82d6add9cf5b7b795ef86e1d3754b1c3804cbe17...
207,WESTERN WATER CATCHMENT,2000,None,None,None,0f71251b271d21f1d7a1fc50a28583a784ea1edf5611e3...
208,WESTERN WATER CATCHMENT,2010,None,None,None,2d25caddf7019a5a33519f4c1aa71d354ff10014404d3a...

In [158]:
df_dwelling[df_dwelling.isnull().any(axis=1)]

,planning_area,year,hdb_1_and_2_room_flats,hdb_3_room_flats,hdb_4_room_flats,hdb_5_room_and_executive_flats,condominiums_and_other_apartments,landed_properties,others,_fp
12,BOON LAY,2010,None,None,None,None,None,None,None,cef0fb519734d3a76a9499d2dc610ba239c2fd683bf774...
13,BOON LAY,2015,None,None,None,None,None,None,None,1b8f834a1339203ecd58a34749245ed91c85033020f06f...
15,BOON LAY/PIONEER,2000,None,None,None,None,None,None,None,5cb4d075a11fdb724e5eb60b5f9e13a873659dc6aadb8b...
32,CENTRAL WATER CATCHMENT,2000,None,None,None,None,None,None,None,f23853b18d3d152b33eab7442c92d9f2cf81cc7e8f1aa2...
33,CENTRAL WATER CATCHMENT,2010,None,None,None,None,None,None,None,11915ad903785cec04e5e2f2b9b8fa45295f9daf270154...
...,...,...,...,...,...,...,...,...,...,...
204,WESTERN ISLANDS,2010,None,None,None,None,None,None,None,fc426c251889e6711a04cc95bb5e80482aae57776f3203...
205,WESTERN ISLANDS,2015,None,None,None,None,None,None,None,13b51e3403fce6c88b10be5a6d3415f3890d93543a8ffc...
207,WESTERN WATER CATCHMENT,2000,None,None,None,None,None,None,None,1a2b6591c9d44e0f10f28cae2270fe6fadde830a45420e...
208,WESTERN WATER CATCHMENT,2010,None,None,None,None,None,None,None,80b94693dac3b96dcb2c144fa44cad89a877a2ddb99de6...
209,WESTERN WATER CATCHMENT,2015,None,None,None,None,None,None,None,181a2fae1d3fae9f046764056569abbbfcf065fc2cea0d...

## **Exploratory Data Analysis on Type of Dwelling**

In [159]:
df_dwelling = df_dwelling.fillna(0)

dwelling_cols = [
    'hdb_1_and_2_room_flats',
    'hdb_3_room_flats',
    'hdb_4_room_flats',
    'hdb_5_room_and_executive_flats',
    'condominiums_and_other_apartments',
    'landed_properties',
    'others'
]

df_dwelling[dwelling_cols] = df_dwelling[dwelling_cols].apply(
    pd.to_numeric, errors='coerce'
)

In [160]:
df_dwelling['total_dwelling_units'] = df_dwelling[dwelling_cols].sum(axis=1)

df_dwelling['pct_hdb_1_and_2_room_flats'] = df_dwelling['hdb_1_and_2_room_flats'] / df_dwelling['total_dwelling_units']
df_dwelling['pct_hdb_3_room_flats'] = df_dwelling['hdb_3_room_flats'] / df_dwelling['total_dwelling_units']
df_dwelling['pct_hdb_4_room_flats'] = df_dwelling['hdb_4_room_flats'] / df_dwelling['total_dwelling_units']
df_dwelling['pct_hdb_5_room_and_executive_flats'] = df_dwelling['hdb_5_room_and_executive_flats'] / df_dwelling['total_dwelling_units']
df_dwelling['pct_condominiums_and_other_apartments'] = df_dwelling['condominiums_and_other_apartments'] / df_dwelling['total_dwelling_units']
df_dwelling['pct_landed_properties'] = df_dwelling['landed_properties'] / df_dwelling['total_dwelling_units']

In [161]:
df_dwelling_2020 = df_dwelling[df_dwelling['year'] == '2020'].copy() # note that year is a string, not an integer

pct_cols = [col for col in df_dwelling_2020.columns if col.startswith('pct_')]

for col in pct_cols:
    s = pd.to_numeric(df_dwelling_2020[col], errors='coerce')
    s = s[s > 0]   # exclude zeros and NaNs

    if s.empty:
        print(f"\n{col}")
        print("No positive values in 2020")
        continue

    max_idx = s.idxmax()
    min_idx = s.idxmin()

    max_row = df_dwelling_2020.loc[max_idx]
    min_row = df_dwelling_2020.loc[min_idx]

    print(f"\n{col}")
    print(f"Highest: {max_row['planning_area']} ({max_row[col]})")
    print(f"Lowest: {min_row['planning_area']} ({min_row[col]})")

pct_hdb_1_and_2_room_flats
Highest: OUTRAM (0.35879284649776455)
Lowest: BUKIT TIMAH (0.005972696245733789)

pct_hdb_3_room_flats
Highest: ANG MO KIO (0.39998339422118895)
Lowest: TANGLIN (0.0026455026455026454)

pct_hdb_4_room_flats
Highest: YISHUN (0.4254870495868865)
Lowest: TANGLIN (0.009952128999748048)

pct_hdb_5_room_and_executive_flats
Highest: PASIR RIS (0.3834992633599714)
Lowest: TANGLIN (0.010833963214915596)

pct_condominiums_and_other_apartments
Highest: RIVER VALLEY (0.9358651911468813)
Lowest: OUTRAM (0.05216095380029806)

pct_landed_properties
Highest: BUKIT TIMAH (0.37229806598407283)
Lowest: PUNGGOL (0.0012285231015757144)

## **Exploratory Data Analysis on Transport to School**

In [162]:
df_transport_school = df_transport_school.fillna(0)

transport_school_cols = [
    'bus', 'mrt', 'mrt_bus', 'mrt_car',
    'mrt_other', 'taxi', 'car', 'pvt_chartered_bus', 'lorry_pickup',
    'motorcycle_scooter', 'others', 'no_transport_required',
    'other_combi_mrt_or_bus', 'mrt_lrt_only', 'mrt_lrt_and_bus',
    'other_combi_mrt_lrt_or_bus', 'taxi_pvt_hire_car_only',
    'pvt_chartered_bus_van'
]

df_transport_school[transport_school_cols] = df_transport_school[transport_school_cols].apply(
    pd.to_numeric, errors='coerce'
)

In [163]:
df_transport_school['total_transport_school'] = df_transport_school[transport_school_cols].sum(axis=1)

df_transport_school['pct_bus'] = df_transport_school['bus'] / df_transport_school['total_transport_school']
df_transport_school['pct_mrt'] = df_transport_school['mrt'] / df_transport_school['total_transport_school']
df_transport_school['pct_mrt_bus'] = df_transport_school['mrt_bus'] / df_transport_school['total_transport_school']
df_transport_school['pct_car'] = df_transport_school['car'] / df_transport_school['total_transport_school']
df_transport_school['pct_mrt_lrt_only'] = df_transport_school['mrt_lrt_only'] / df_transport_school['total_transport_school']
df_transport_school['pct_mrt_lrt_and_bus'] = df_transport_school['mrt_lrt_and_bus'] / df_transport_school['total_transport_school']

In [164]:
df_transport_school_2020 = df_transport_school[df_transport_school['year'] == '2020'].copy() # note that year is a string, not an integer

pct_cols = [col for col in df_transport_school_2020.columns if col.startswith('pct_')]

for col in pct_cols:
    s = pd.to_numeric(df_transport_school_2020[col], errors='coerce')
    s = s[s > 0]   # exclude zeros and NaNs

    if s.empty:
        print(f"\n{col}")
        print("No positive values in 2020")
        continue

    max_idx = s.idxmax()
    min_idx = s.idxmin()

    max_row = df_transport_school_2020.loc[max_idx]
    min_row = df_transport_school_2020.loc[min_idx]

    print(f"\n{col}")
    print(f"Highest: {max_row['planning_area']} ({max_row[col]})")
    print(f"Lowest: {min_row['planning_area']} ({min_row[col]})")

pct_bus
Highest: JURONG EAST (0.33772958977263534)
Lowest: RIVER VALLEY (0.09216589861751152)

pct_mrt
No positive values in 2020

pct_mrt_bus
No positive values in 2020

pct_car
Highest: TANGLIN (0.364103819784525)
Lowest: WOODLANDS (0.06902245041779925)

pct_mrt_lrt_only
Highest: DOWNTOWN CORE (0.23214285714285715)
Lowest: MARINE PARADE (0.02807060554057367)

pct_mrt_lrt_and_bus
Highest: CHOA CHU KANG (0.3073444565725869)
Lowest: TANGLIN (0.09720861900097943)