In [6]:
from sqlalchemy import create_engine
import pandas as pd

In [7]:
engine_hdb = create_engine('mysql://bt4301:password@localhost:3306/HDB_Data')

str_sql = f'''
SELECT * FROM raw_onemap_transport_school
'''
df_transport_school = pd.read_sql(sql=str_sql, con=engine_hdb)

str_sql = f'''
SELECT * FROM raw_onemap_transport_work
'''
df_transport_work = pd.read_sql(sql=str_sql, con=engine_hdb)

str_sql = f'''
SELECT * FROM raw_onemap_dwelling
'''
df_dwelling = pd.read_sql(sql=str_sql, con=engine_hdb)

str_sql = f'''
SELECT * FROM raw_onemap_tenancy
'''
df_tenancy = pd.read_sql(sql=str_sql, con=engine_hdb)

engine_hdb.dispose()

## **Finding DataFrames with Nulls**

In [8]:
for df in [df_transport_school, df_transport_work, df_dwelling, df_tenancy]:
    print(df.isna().sum())

planning_area                  0
year                           0
bus                           42
mrt                           42
mrt_bus                       42
mrt_car                       42
mrt_other                     42
taxi                          42
car                           42
pvt_chartered_bus             42
lorry_pickup                  42
motorcycle_scooter            42
others                        42
no_transport_required         42
other_combi_mrt_or_bus        42
mrt_lrt_only                  42
mrt_lrt_and_bus               42
other_combi_mrt_lrt_or_bus    42
taxi_pvt_hire_car_only        42
pvt_chartered_bus_van         42
_fp                            0
dtype: int64
planning_area                  0
year                           0
bus                           42
mrt                           42
mrt_bus                       42
mrt_car                       42
mrt_other                     42
taxi                          42
car                           42
pvt_chartered_bus             42
lorry_pickup                  42
motorcycle_scooter            42
others                        42
no_transport_required         42
other_combi_mrt_or_bus        42
mrt_lrt_only                  42
mrt_lrt_and_bus               42
other_combi_mrt_lrt_or_bus    42
taxi_pvt_hire_car_only        42
pvt_chartered_bus_van         42
_fp                            0
dtype: int64
planning_area                         0
year                                  0
hdb_1_and_2_room_flats               69
hdb_3_room_flats                     69
hdb_4_room_flats                     69
hdb_5_room_and_executive_flats       69
condominiums_and_other_apartments    69
landed_properties                    69
others                               69
_fp                                   0
dtype: int64
planning_area     0
year              0
owner            42
tenant           42
others           42
_fp               0
dtype: int64

In [9]:
df_transport_school[df_transport_school.isnull().any(axis=1)]

,planning_area,year,bus,mrt,mrt_bus,mrt_car,mrt_other,taxi,car,pvt_chartered_bus,...,motorcycle_scooter,others,no_transport_required,other_combi_mrt_or_bus,mrt_lrt_only,mrt_lrt_and_bus,other_combi_mrt_lrt_or_bus,taxi_pvt_hire_car_only,pvt_chartered_bus_van,_fp
3,WESTERN WATER CATCHMENT,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88746e54bf3ec353c10dfc282bdbb7876ea8ae902a406d...
5,WESTERN ISLANDS,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21984e07f53c3ad2670b4be7a17fc40b05bd1f46e0f76c...
6,CHANGI BAY,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,07118f349a63ecbe197c7fd462c0b503fd8fef875ceb28...
8,CENTRAL WATER CATCHMENT,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,470a762d4f68790166da8886933789b244f5db616e676e...
17,BOON LAY/PIONEER,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,eb8b85621f401a600ea0352008ca7c092e20aa3280c77c...
18,SINGAPORE RIVER,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b429fc2a936a60a381a923e2132a50ccdbb15d43c63305...
20,SOUTHERN ISLANDS,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6a1d58626774c67b3634c8bbc69c2ef370d2ddd93bd12f...
21,MARINA SOUTH,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15b38dccc6e30388238e0ae7ea107035e050d408bc779b...
22,SUNGEI KADUT,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,800b75b7616bc0c8487170b16047a01fbb24fabb7817ad...
23,SELETAR,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b2854239c1e5b4e22a62a135f63ae1d050e03ebc2d112d...
24,SIMPANG,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0a2e524dd1fefb1dca564eba604e4d46e92321019a55ce...
25,TENGAH,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6befaa756eac02f68af476b1989117f26e4b003afc2940...
31,LIM CHU KANG,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,daff0cd619a96139c921d557bc957cbb1b9f41531e094d...
32,MANDAI,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2a80ce1e6613298b7c68c7d0791f4ba7027cd46645a298...
33,MUSEUM,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5e94cf0abfe94146e0002703c9c52048b273b7ee4a5cf0...
34,NORTH-EASTERN ISLANDS,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b18ca9562e901e967d3ef6935aacef81510b4c5f6b1904...
35,MARINA EAST,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0196860ea7298e822bc8839a044df79f9ac81e8446e2cd...
39,STRAITS VIEW,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2cb973bd06607ce3e6053d9f19e1155ab5b0f6344bd731...
42,ORCHARD,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,c95db05065acacbfa6d256b013e410a2805d02a57ec81a...
43,PUNGGOL,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0b8c0b675a47b9ada10cfb3e0a02e76f79d9233a5d9b30...
44,PAYA LEBAR,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4ef1c3158060b6fdc02ab0797a1daa4f9a9aef32ca176e...
52,TUAS,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,68fed366ff0e48c123342d49a99f92bbfce2dd8f0be162...
56,SELETAR,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1aa13db3b3890aa352a9745c5c046129e9e04918aca5a0...
57,SIMPANG,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8acc9322986d90b8b2f454c359f81b2c402c85448765ed...
59,SOUTHERN ISLANDS,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2e24a54cb3f8512dd82da45839251b817e21f3cb490861...
61,WESTERN WATER CATCHMENT,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,de81ab74db93225a0efd4d686ecc44c191419a7a066941...
63,LIM CHU KANG,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,fc4ec02be9730a4889f9a158193795f1d6676a9e6aaf1a...
64,NORTH-EASTERN ISLANDS,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ec6f589f167dff0270584b35bd9e938441b18fa1fbf2ff...
66,WESTERN ISLANDS,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,c171fec842746229dd3b419a934f5d5b0a66c90b609cca...
70,TENGAH,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,eff2ebe648f82b8e56c1ddd11f815b6720bb32ee82e22b...
73,PIONEER,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5741392a08a55db9a270c462c18e3793954316ac51bbdf...
78,PAYA LEBAR,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,884eb3f5cfa60c2dd983354ae9acb757cb3e7bdf76a896...
83,SUNGEI KADUT,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,69028dc9c56c309d20317ea27ae7a9f63a9a2283889616...
86,BOON LAY,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bb97f5aa45e7dec920ac0ed689bb04be5755ab866ebe11...
89,MARINA SOUTH,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16d60bf996ddad4b3e559504026506569b191ca53db071...
90,STRAITS VIEW,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0ea8ca389dffdf7ba5d3530809577aec3c97b80d7affa8...
91,MARINA EAST,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8c3c4842cc0de970d9060acc4ca32119ef3a28db8e353d...
96,TUAS,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12fa4e746e9134ed79720b5fdfa8051d5a3c77a1026940...
99,CENTRAL WATER CATCHMENT,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5d6fe7be6ec5cddd56060deff5a5d5820fc0ca4f0b2e17...
100,CHANGI BAY,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6389cf880818da2d1fc009e2cc7a56d2b93de37591fe98...
102,ORCHARD,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4f68da6bc09962cb3ffe216bde201e6cc7a171b6c6e044...
103,MUSEUM,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ca502f327393835e3ef2aab502670eb628f817293ee027...

In [10]:
df_transport_work[df_transport_work.isnull().any(axis=1)]

,planning_area,year,bus,mrt,mrt_bus,mrt_car,mrt_other,taxi,car,pvt_chartered_bus,...,motorcycle_scooter,others,no_transport_required,other_combi_mrt_or_bus,mrt_lrt_only,mrt_lrt_and_bus,other_combi_mrt_lrt_or_bus,taxi_pvt_hire_car_only,pvt_chartered_bus_van,_fp
3,WESTERN WATER CATCHMENT,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88746e54bf3ec353c10dfc282bdbb7876ea8ae902a406d...
5,WESTERN ISLANDS,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21984e07f53c3ad2670b4be7a17fc40b05bd1f46e0f76c...
6,CHANGI BAY,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,07118f349a63ecbe197c7fd462c0b503fd8fef875ceb28...
8,CENTRAL WATER CATCHMENT,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,470a762d4f68790166da8886933789b244f5db616e676e...
17,BOON LAY/PIONEER,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,eb8b85621f401a600ea0352008ca7c092e20aa3280c77c...
18,SINGAPORE RIVER,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b429fc2a936a60a381a923e2132a50ccdbb15d43c63305...
20,SOUTHERN ISLANDS,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6a1d58626774c67b3634c8bbc69c2ef370d2ddd93bd12f...
21,MARINA SOUTH,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15b38dccc6e30388238e0ae7ea107035e050d408bc779b...
22,SUNGEI KADUT,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,800b75b7616bc0c8487170b16047a01fbb24fabb7817ad...
23,SELETAR,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b2854239c1e5b4e22a62a135f63ae1d050e03ebc2d112d...
24,SIMPANG,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0a2e524dd1fefb1dca564eba604e4d46e92321019a55ce...
25,TENGAH,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6befaa756eac02f68af476b1989117f26e4b003afc2940...
31,LIM CHU KANG,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,daff0cd619a96139c921d557bc957cbb1b9f41531e094d...
32,MANDAI,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2a80ce1e6613298b7c68c7d0791f4ba7027cd46645a298...
33,MUSEUM,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5e94cf0abfe94146e0002703c9c52048b273b7ee4a5cf0...
34,NORTH-EASTERN ISLANDS,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b18ca9562e901e967d3ef6935aacef81510b4c5f6b1904...
35,MARINA EAST,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0196860ea7298e822bc8839a044df79f9ac81e8446e2cd...
39,STRAITS VIEW,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2cb973bd06607ce3e6053d9f19e1155ab5b0f6344bd731...
42,ORCHARD,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,c95db05065acacbfa6d256b013e410a2805d02a57ec81a...
43,PUNGGOL,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0b8c0b675a47b9ada10cfb3e0a02e76f79d9233a5d9b30...
44,PAYA LEBAR,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4ef1c3158060b6fdc02ab0797a1daa4f9a9aef32ca176e...
52,TUAS,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,68fed366ff0e48c123342d49a99f92bbfce2dd8f0be162...
56,SELETAR,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1aa13db3b3890aa352a9745c5c046129e9e04918aca5a0...
57,SIMPANG,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8acc9322986d90b8b2f454c359f81b2c402c85448765ed...
59,SOUTHERN ISLANDS,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2e24a54cb3f8512dd82da45839251b817e21f3cb490861...
61,WESTERN WATER CATCHMENT,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,de81ab74db93225a0efd4d686ecc44c191419a7a066941...
63,LIM CHU KANG,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,fc4ec02be9730a4889f9a158193795f1d6676a9e6aaf1a...
64,NORTH-EASTERN ISLANDS,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ec6f589f167dff0270584b35bd9e938441b18fa1fbf2ff...
66,WESTERN ISLANDS,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,c171fec842746229dd3b419a934f5d5b0a66c90b609cca...
70,TENGAH,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,eff2ebe648f82b8e56c1ddd11f815b6720bb32ee82e22b...
73,PIONEER,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5741392a08a55db9a270c462c18e3793954316ac51bbdf...
78,PAYA LEBAR,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,884eb3f5cfa60c2dd983354ae9acb757cb3e7bdf76a896...
83,SUNGEI KADUT,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,69028dc9c56c309d20317ea27ae7a9f63a9a2283889616...
86,BOON LAY,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bb97f5aa45e7dec920ac0ed689bb04be5755ab866ebe11...
89,MARINA SOUTH,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16d60bf996ddad4b3e559504026506569b191ca53db071...
90,STRAITS VIEW,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0ea8ca389dffdf7ba5d3530809577aec3c97b80d7affa8...
91,MARINA EAST,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8c3c4842cc0de970d9060acc4ca32119ef3a28db8e353d...
96,TUAS,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12fa4e746e9134ed79720b5fdfa8051d5a3c77a1026940...
99,CENTRAL WATER CATCHMENT,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5d6fe7be6ec5cddd56060deff5a5d5820fc0ca4f0b2e17...
100,CHANGI BAY,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6389cf880818da2d1fc009e2cc7a56d2b93de37591fe98...
102,ORCHARD,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4f68da6bc09962cb3ffe216bde201e6cc7a171b6c6e044...
103,MUSEUM,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ca502f327393835e3ef2aab502670eb628f817293ee027...

In [11]:
df_tenancy[df_tenancy.isnull().any(axis=1)]

,planning_area,year,owner,tenant,others,_fp
3,WESTERN WATER CATCHMENT,2000,NaN,NaN,NaN,0f71251b271d21f1d7a1fc50a28583a784ea1edf5611e3...
5,WESTERN ISLANDS,2000,NaN,NaN,NaN,ebd18da74601f9cd1854ed96c4ae8aee190d86863e4fba...
6,CHANGI BAY,2000,NaN,NaN,NaN,8c4d0a58f5fe122de9bd61177b07615d0e601baf1b81fc...
8,CENTRAL WATER CATCHMENT,2000,NaN,NaN,NaN,2b6ce587e517d7f779ba7d5cf421ed28df4b300b54b827...
17,BOON LAY/PIONEER,2000,NaN,NaN,NaN,9fbed945cec7d33b2d310ab9fcddfe333da0d8789b6bc4...
18,SINGAPORE RIVER,2000,NaN,NaN,NaN,de1857fbd566125a2dbed699221a11da3930438343cfdd...
20,SOUTHERN ISLANDS,2000,NaN,NaN,NaN,7f8f60e911fe3c8ae419d9ad1bb00b10ef8c7fd31c3dd2...
21,MARINA SOUTH,2000,NaN,NaN,NaN,45b170b9dd68400f76b5d9946b639d2242de0589028f06...
22,SUNGEI KADUT,2000,NaN,NaN,NaN,0f18b824100129e65ee411d496c4a89173ac0eb0d6eb13...
23,SELETAR,2000,NaN,NaN,NaN,ef6ae9f8367224ab63ada23a08a9f680e4eb1480bdfc20...
24,SIMPANG,2000,NaN,NaN,NaN,6dae270a031d340fb19aa450512153025a61d3fe558fd7...
25,TENGAH,2000,NaN,NaN,NaN,74a516565fec0d2ecd795791b8c4803def48c805ad143e...
31,LIM CHU KANG,2000,NaN,NaN,NaN,0800d628e8b4bc70a20016898b94387003833e45d49406...
32,MANDAI,2000,NaN,NaN,NaN,d3d60c30ff781feaf070ca9e6f4fe480b92d67e3f88b5e...
33,MUSEUM,2000,NaN,NaN,NaN,7de08ec563decf7af8fd6f19899ed0f9036ccc2f5a5965...
34,NORTH-EASTERN ISLANDS,2000,NaN,NaN,NaN,8bab7408f238a5f13fb76a8a00292d0c45abe4a83fe698...
35,MARINA EAST,2000,NaN,NaN,NaN,7530ac3714b6fca90a30045b5fc4995f80f4b7b49d49e7...
39,STRAITS VIEW,2000,NaN,NaN,NaN,42540d151dfdf5ebf379bc4d31905fcd7a34b714903475...
42,ORCHARD,2000,NaN,NaN,NaN,da264e14e6cbbb444dcc0a3f9d39c360c55b960e8a61fd...
43,PUNGGOL,2000,NaN,NaN,NaN,59359e3fa36481f55dca71fbec33dade5239d5b99b8e03...
44,PAYA LEBAR,2000,NaN,NaN,NaN,54e1deb5c3c4a07869fc641496064a697d9fd2604190cd...
52,TUAS,2000,NaN,NaN,NaN,2b085a2ccb351e5c49d6a7713463a7a135074311c26c53...
56,SELETAR,2010,NaN,NaN,NaN,76b7d091b7d46902384aea7b257e4ca564413b1c3c7180...
57,SIMPANG,2010,NaN,NaN,NaN,8ff2eeb2da16b05a226204fd93cc2ce7c6e870909ea4d6...
59,SOUTHERN ISLANDS,2010,NaN,NaN,NaN,28e888da7e9d9c009fb335872291db01e7f748dc01bae8...
61,WESTERN WATER CATCHMENT,2010,NaN,NaN,NaN,2d25caddf7019a5a33519f4c1aa71d354ff10014404d3a...
63,LIM CHU KANG,2010,NaN,NaN,NaN,46c91cddbbcf1e03868527e45b2d2a06af702efd822b69...
64,NORTH-EASTERN ISLANDS,2010,NaN,NaN,NaN,b612a87dad0134f23cc981f720872b60cbdb09b6d40e05...
66,WESTERN ISLANDS,2010,NaN,NaN,NaN,955adb82d6add9cf5b7b795ef86e1d3754b1c3804cbe17...
70,TENGAH,2010,NaN,NaN,NaN,6659a4fb0e2955e9f510b83372439440546fdaf665f852...
73,PIONEER,2010,NaN,NaN,NaN,4cbf6ff15555c89544bf63ab5e58052ddf9f0055a35e49...
78,PAYA LEBAR,2010,NaN,NaN,NaN,bd13e754e569583c198c3c653098f004e3e282542aa199...
83,SUNGEI KADUT,2010,NaN,NaN,NaN,c9621fb1e4356952d35dfa10608193f82f3cd731ed00a2...
86,BOON LAY,2010,NaN,NaN,NaN,8c78d2b1420448080f7c1ac611dde94a2825640d7074e6...
89,MARINA SOUTH,2010,NaN,NaN,NaN,74688c0a23875723a141c11c66b1f91ea6c205c4776451...
90,STRAITS VIEW,2010,NaN,NaN,NaN,6b5cab6167c84e7cfeda5e483cffd2f0e51641e63676b0...
91,MARINA EAST,2010,NaN,NaN,NaN,9152ecd9ecb12b7befaa2dcc66e7b15827be99451bb7f4...
96,TUAS,2010,NaN,NaN,NaN,0e100982b08b861e94d1d7fa3e86281ef0613079f8b597...
99,CENTRAL WATER CATCHMENT,2010,NaN,NaN,NaN,d6c6b4baef978841b21c66d3a29a27244a08f6a03af0ef...
100,CHANGI BAY,2010,NaN,NaN,NaN,49d8fc9b150cab32a3f32b4ee89e212a63ca5ac1467922...
102,ORCHARD,2010,NaN,NaN,NaN,01f8b5d95b4f542730b325b6c2ee79c145f25cb9bff36f...
103,MUSEUM,2010,NaN,NaN,NaN,d81b895d4d30034605a323748065ac52599059388ad2a9...

In [12]:
df_dwelling[df_dwelling.isnull().any(axis=1)]

,planning_area,year,hdb_1_and_2_room_flats,hdb_3_room_flats,hdb_4_room_flats,hdb_5_room_and_executive_flats,condominiums_and_other_apartments,landed_properties,others,_fp
3,WESTERN WATER CATCHMENT,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1a2b6591c9d44e0f10f28cae2270fe6fadde830a45420e...
5,WESTERN ISLANDS,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,179f0e21d0a3ea5536d6cb2e05df2b20f498a049388229...
6,CHANGI BAY,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,a2a78a78f844215a87f077b933d852ec0223b2da702134...
8,CENTRAL WATER CATCHMENT,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f23853b18d3d152b33eab7442c92d9f2cf81cc7e8f1aa2...
17,BOON LAY/PIONEER,2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5cb4d075a11fdb724e5eb60b5f9e13a873659dc6aadb8b...
...,...,...,...,...,...,...,...,...,...,...
155,CHANGI BAY,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03e2b9e06da26c0c5b02f3c0e1c7900ec57f9595d14e4d...
157,PAYA LEBAR,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,c0ed4d6bc0bb266a42b45a80693b5786fd6d01ca50bc9b...
161,CENTRAL WATER CATCHMENT,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f2ef04aa31f64eb471dc8e1c18eea35abfd1cd14401807...
162,RIVER VALLEY,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,e30b8befc419feb4d8b8bc2beae59399635e222b57cab9...
163,ROCHOR,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8d3c85e2afc7e15d29f910dd6f5a6d39166ba2e47af609...

## **Exploratory Data Analysis on Type of Dwelling**

In [13]:
df_dwelling = df_dwelling.fillna(0)

dwelling_cols = [
    'hdb_1_and_2_room_flats',
    'hdb_3_room_flats',
    'hdb_4_room_flats',
    'hdb_5_room_and_executive_flats',
    'condominiums_and_other_apartments',
    'landed_properties',
    'others'
]

df_dwelling[dwelling_cols] = df_dwelling[dwelling_cols].apply(
    pd.to_numeric, errors='coerce'
)

In [14]:
df_dwelling['total_dwelling_units'] = df_dwelling[dwelling_cols].sum(axis=1)

df_dwelling['pct_hdb_1_and_2_room_flats'] = df_dwelling['hdb_1_and_2_room_flats'] / df_dwelling['total_dwelling_units']
df_dwelling['pct_hdb_3_room_flats'] = df_dwelling['hdb_3_room_flats'] / df_dwelling['total_dwelling_units']
df_dwelling['pct_hdb_4_room_flats'] = df_dwelling['hdb_4_room_flats'] / df_dwelling['total_dwelling_units']
df_dwelling['pct_hdb_5_room_and_executive_flats'] = df_dwelling['hdb_5_room_and_executive_flats'] / df_dwelling['total_dwelling_units']
df_dwelling['pct_condominiums_and_other_apartments'] = df_dwelling['condominiums_and_other_apartments'] / df_dwelling['total_dwelling_units']
df_dwelling['pct_landed_properties'] = df_dwelling['landed_properties'] / df_dwelling['total_dwelling_units']

In [15]:
df_dwelling_2020 = df_dwelling[df_dwelling['year'] == '2020'].copy() # note that year is a string, not an integer

pct_cols = [col for col in df_dwelling_2020.columns if col.startswith('pct_')]

for col in pct_cols:
    s = pd.to_numeric(df_dwelling_2020[col], errors='coerce')
    s = s[s > 0]   # exclude zeros and NaNs

    if s.empty:
        print(f"\n{col}")
        print("No positive values in 2020")
        continue

    max_idx = s.idxmax()
    min_idx = s.idxmin()

    max_row = df_dwelling_2020.loc[max_idx]
    min_row = df_dwelling_2020.loc[min_idx]

    print(f"\n{col}")
    print(f"Highest: {max_row['planning_area']} ({max_row[col]})")
    print(f"Lowest: {min_row['planning_area']} ({min_row[col]})")

pct_hdb_1_and_2_room_flats
No positive values in 2020

pct_hdb_3_room_flats
No positive values in 2020

pct_hdb_4_room_flats
No positive values in 2020

pct_hdb_5_room_and_executive_flats
No positive values in 2020

pct_condominiums_and_other_apartments
No positive values in 2020

pct_landed_properties
No positive values in 2020

## **Exploratory Data Analysis on Transport to School**

In [16]:
df_transport_school = df_transport_school.fillna(0)

transport_school_cols = [
    'bus', 'mrt', 'mrt_bus', 'mrt_car',
    'mrt_other', 'taxi', 'car', 'pvt_chartered_bus', 'lorry_pickup',
    'motorcycle_scooter', 'others', 'no_transport_required',
    'other_combi_mrt_or_bus', 'mrt_lrt_only', 'mrt_lrt_and_bus',
    'other_combi_mrt_lrt_or_bus', 'taxi_pvt_hire_car_only',
    'pvt_chartered_bus_van'
]

df_transport_school[transport_school_cols] = df_transport_school[transport_school_cols].apply(
    pd.to_numeric, errors='coerce'
)

In [17]:
df_transport_school['total_transport_school'] = df_transport_school[transport_school_cols].sum(axis=1)

df_transport_school['pct_bus'] = df_transport_school['bus'] / df_transport_school['total_transport_school']
df_transport_school['pct_mrt'] = df_transport_school['mrt'] / df_transport_school['total_transport_school']
df_transport_school['pct_mrt_bus'] = df_transport_school['mrt_bus'] / df_transport_school['total_transport_school']
df_transport_school['pct_car'] = df_transport_school['car'] / df_transport_school['total_transport_school']
df_transport_school['pct_mrt_lrt_only'] = df_transport_school['mrt_lrt_only'] / df_transport_school['total_transport_school']
df_transport_school['pct_mrt_lrt_and_bus'] = df_transport_school['mrt_lrt_and_bus'] / df_transport_school['total_transport_school']

In [18]:
df_transport_school_2020 = df_transport_school[df_transport_school['year'] == '2020'].copy() # note that year is a string, not an integer

pct_cols = [col for col in df_transport_school_2020.columns if col.startswith('pct_')]

for col in pct_cols:
    s = pd.to_numeric(df_transport_school_2020[col], errors='coerce')
    s = s[s > 0]   # exclude zeros and NaNs

    if s.empty:
        print(f"\n{col}")
        print("No positive values in 2020")
        continue

    max_idx = s.idxmax()
    min_idx = s.idxmin()

    max_row = df_transport_school_2020.loc[max_idx]
    min_row = df_transport_school_2020.loc[min_idx]

    print(f"\n{col}")
    print(f"Highest: {max_row['planning_area']} ({max_row[col]})")
    print(f"Lowest: {min_row['planning_area']} ({min_row[col]})")

pct_bus
No positive values in 2020

pct_mrt
No positive values in 2020

pct_mrt_bus
No positive values in 2020

pct_car
No positive values in 2020

pct_mrt_lrt_only
No positive values in 2020

pct_mrt_lrt_and_bus
No positive values in 2020